outfoxx/swiftpoet

src/main/java/io/outfoxx/swiftpoet/PropertySpec.kt
src/test/java/io/outfoxx/swiftpoet/test/PropertySpecTests.kt

A name will automatically be escaped if it matches a keyword or is not a valid bare identifier.
Closes #2.

Remove valid property name check

---

src/main/java/io/outfoxx/swiftpoet/DeclaredTypeName.kt
src/main/java/io/outfoxx/swiftpoet/TypeSpec.kt
src/main/java/io/outfoxx/swiftpoet/Util.kt
src/test/java/io/outfoxx/swiftpoet/test/ClassSpecTests.kt
src/test/java/io/outfoxx/swiftpoet/test/PropertySpecTests.kt

This allows things like:
```
struct `Type` {}
```
and makes sure it's escaped properly, both in its declaration and when referenced.

Escape reserved type names

---

src/main/java/io/outfoxx/swiftpoet/FileSpec.kt

KotlinPoet always invokes this method even when you don't have a package from https://github.com/square/kotlinpoet/pull/500. Since Swift isn't nesting code in folders there's less of a need for this change. But without it you force the caller to remember to do it themselves.
Additionally, the `Files.notExists` check above doesn't make sense without this change since it allows the absence of the directory to pass the check and then immediately will crash trying to write to the non-existent dir.
That being said, doing this yourself isn't hard, it's just that you have to remember.
Up to you. I don't think it's an essential change just figured I'd throw it up and see what you thought.

Create output directory if it does not exist

---

src/main/java/io/outfoxx/swiftpoet/TypeSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/EnumSpecTests.kt

An enum with no cases is valid in Swift, and such a definition is sometimes useful to provide "namespacing", such as:
```
enum Foo {
struct Bar {…}
}
```

Remove requirement that enums have at least one case

---

src/main/java/io/outfoxx/swiftpoet/FileMemberSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileSpec.kt
src/main/java/io/outfoxx/swiftpoet/ImportSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/FileSpecTests.kt

Allows any file import or member to be guarded (`#if/#endif`) and/or documented.
Documentation at the member level will be output immediately prior to the member spec's own documentation.

Support guarding & documenting imports & members

---

src/main/java/io/outfoxx/swiftpoet/AnyTypeSpec.kt
src/main/java/io/outfoxx/swiftpoet/ExtensionSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileMemberSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileSpec.kt
src/main/java/io/outfoxx/swiftpoet/TypeAliasSpec.kt
src/main/java/io/outfoxx/swiftpoet/TypeSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/ClassSpecTests.kt
src/test/java/io/outfoxx/swiftpoet/test/ExtensionSpecTests.kt
src/test/java/io/outfoxx/swiftpoet/test/TypeAliasSpecTests.kt

Removes all specializations of functions for `TypeSpec` & `TypeAliasSpec`; now all use single set of `AnyTypeSpec` methods.
Fixes #17

Add AnyTypeSpec as ancestor to TypeSpec & TypeAliasSpec

---

src/main/java/io/outfoxx/swiftpoet/CodeBlock.kt
src/main/java/io/outfoxx/swiftpoet/FunctionSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/CodeBlockTests.kt

Support generating switch via `beginControlFlow`/`endControlFlow` without indent

---

src/main/java/io/outfoxx/swiftpoet/AnyTypeSpec.kt
src/main/java/io/outfoxx/swiftpoet/CodeBlock.kt
src/main/java/io/outfoxx/swiftpoet/CodeWriter.kt
src/main/java/io/outfoxx/swiftpoet/ExtensionSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileMemberSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileSpec.kt
src/main/java/io/outfoxx/swiftpoet/TypeSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/CodeBlockTests.kt

Fixes and adds test for a number of things that were still using `TypeSpec` and would fail or emit incorrect code when using `TypeAliasSpec`/

Replace remaining incorrect usages to TypeSpec with AnyTypeSpec

---

src/main/java/io/outfoxx/swiftpoet/CodeBlock.kt
src/test/java/io/outfoxx/swiftpoet/test/CodeBlockTests.kt

When calling `nextControlFlow` with a simple construct (e.g. `else`) there is no longer an extra space present.
Also, defaults the `controlFlowCode` argument to empty string for convenience.
Fixes #35

Fix spacing for simple continuing control flow constructs (e.g. “else”)

---

src/main/java/io/outfoxx/swiftpoet/AnyTypeSpec.kt
src/main/java/io/outfoxx/swiftpoet/AttributeSpec.kt
src/main/java/io/outfoxx/swiftpoet/AttributedSpec.kt
src/main/java/io/outfoxx/swiftpoet/EnumerationCaseSpec.kt
src/main/java/io/outfoxx/swiftpoet/ExtensionSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileMemberSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileSpec.kt
src/main/java/io/outfoxx/swiftpoet/FunctionSpec.kt
src/main/java/io/outfoxx/swiftpoet/ImportSpec.kt
src/main/java/io/outfoxx/swiftpoet/ParameterSpec.kt
src/main/java/io/outfoxx/swiftpoet/PropertySpec.kt
src/main/java/io/outfoxx/swiftpoet/Taggable.kt
src/main/java/io/outfoxx/swiftpoet/TypeAliasSpec.kt
src/main/java/io/outfoxx/swiftpoet/TypeSpec.kt

Allows tagging specs & builders with arbitrary domain specific data.
Note that this is a near exact copy of Taggable from kotlinpoet.

Add Taggable support to all specs & builders

---

src/main/java/io/outfoxx/swiftpoet/NameAllocator.kt

`NameAllocator` handles name collisions when generating code. It supports generating unique names and accessing those unique names later during generation of code referencing those names.
Note this is a nearly identical copy of `NameAllocator` from kotlinpoet.
Fixes #9

Add NameAllocator for handling name collisions

---

src/main/java/io/outfoxx/swiftpoet/DeclaredTypeName.kt
src/test/java/io/outfoxx/swiftpoet/test/FileSpecTests.kt

Using `TypeName.qualifiedTypeName(String)` will produce a type name that is always qualified and will never produce an import statement.

Allow `DeclaredTypeName`s to always be fully qualified.

---

src/main/java/io/outfoxx/swiftpoet/TypeSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/ProtocolSpecTests.kt

As reported on issue #60, the current implementation of the nested protocol rules doesn't account for a couple of scenarios where either the input is allowed but not supported by SwiftPoet, or the output of SwiftPoet is invalid Swift code.
This PR fixes both scenarios:
- it allows protocols to have `TypeAliasSpec` as a nested type
- it doesn't allow protocol to be added as a nested type of any construct
Tests were added for both scenarios.

Fix nested protocol rules

---

src/main/java/io/outfoxx/swiftpoet/ParameterSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/FunctionSpecTests.kt

Declaring a function parameter with the same value for
argumentLabel and parameterSpec produces a warning in xcode (often
treated as error if the compiler setting is enabled). We should handle
this while emitting code and only adding the argumentLabel when its
value is different from parameterName

Ignore argumentLabel when equal to parameterName

---

src/main/java/io/outfoxx/swiftpoet/ParameterizedTypeName.kt
src/test/java/io/outfoxx/swiftpoet/test/FunctionSpecTests.kt

Provides fix and tests to support the creation of an optional closure parameter.
Close #72

Add support for optional closure parameter

---

src/main/java/io/outfoxx/swiftpoet/ExtensionSpec.kt
src/main/java/io/outfoxx/swiftpoet/FileMemberSpec.kt
src/main/java/io/outfoxx/swiftpoet/FunctionSignatureSpec.kt
src/main/java/io/outfoxx/swiftpoet/FunctionSpec.kt
src/main/java/io/outfoxx/swiftpoet/PropertySpec.kt
src/main/java/io/outfoxx/swiftpoet/TypeSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/FunctionSpecTests.kt
src/test/java/io/outfoxx/swiftpoet/test/PropertySpecTests.kt

* Adds new `FunctionSignatureSpec` shared between properties and functions
* subscript properties are built using a new `subscriptBuilder(FunctionSignatureSpec)` factory
Fixes #69

Add support for subscript properties

---

src/main/java/io/outfoxx/swiftpoet/PropertySpec.kt
src/test/java/io/outfoxx/swiftpoet/test/PropertySpecTests.kt

Allows generating property fields with different explicit visibility for setters.
public & private setter
```swift
public private(set) var x: Int
```
standalone private setter
```swift
private(set) var x: Int
```

Support adding visibility to mutable property fields

---

src/main/java/io/outfoxx/swiftpoet/AttributeSpec.kt
src/main/java/io/outfoxx/swiftpoet/CodeWriter.kt
src/main/java/io/outfoxx/swiftpoet/Util.kt
src/test/java/io/outfoxx/swiftpoet/test/AttributeSpecTests.kt
src/test/java/io/outfoxx/swiftpoet/test/UtilTests.kt

A while ago this PR was opened https://github.com/outfoxx/swiftpoet/pull/86 to better handle escaping of strings within attributes.
For Wire we added this temporary commit https://github.com/square/wire/commit/08836c7102c7d9981c588bc5373576491e945b8f to circumvent this issue until a new release of SwiftPoet is ready.
This PR here extends #86 to further use some of the newly added booleans in the Util methods. In particular, `AttributeSpec` now accepts code blocks to properly format strings etc.
This means that in Wire we can delete the above commit and lean on SwiftPoet to do the right thing. The PR also brings some tests present in KotlinPoet.

Improve output of AttributeSpec to accept CodeBlocks.

---

src/main/java/io/outfoxx/swiftpoet/FunctionSignatureSpec.kt
src/main/java/io/outfoxx/swiftpoet/FunctionSpec.kt
src/main/java/io/outfoxx/swiftpoet/PropertySpec.kt
src/test/java/io/outfoxx/swiftpoet/test/FunctionSpecTests.kt

The original problem was that `FunctionSpecTests.testGenSetFunction()` test was failed.
It means you can't generate such code: `func set(property: Swift.String)` with swift poet. Instead of this you will get `set(property)` as result.
This PR fix this issue.

Fix generation functions with 'set' and 'get' names

---

src/test/java/io/outfoxx/swiftpoet/test/NameAllocatorTests.kt

Just increasing test coverage in preparation to have Wire use a NameAllocator for its Swift code-gen part.

Add NameAllocatorTests

---

api/swiftpoet.api
src/main/java/io/outfoxx/swiftpoet/CodeWriter.kt
src/main/java/io/outfoxx/swiftpoet/DeclaredTypeName.kt
src/main/java/io/outfoxx/swiftpoet/FileSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/FileSpecTests.kt

Builds on #90 and fixes nested and same type importing

Fix outstanding cases with importing

---

src/main/java/io/outfoxx/swiftpoet/CodeWriter.kt
src/main/java/io/outfoxx/swiftpoet/ImportSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/FileSpecTests.kt

This does two things...
1. Stops attempting to import "local" types (i.e. types without a module).
2. Requires that names are not blank when building an `ImportSpec`.

Fix incorrect importing of local types

---

src/main/java/io/outfoxx/swiftpoet/CodeWriter.kt
src/test/java/io/outfoxx/swiftpoet/test/FileSpecTests.kt

In [this](https://github.com/outfoxx/swiftpoet/pull/97/files#diff-3eb9e4a966de31a94296a10f7d7ef6030b1fca57b480c78891fb6419bf3eab82R283) PR  if we find ambiguous types we do not qualify them all. The test case was written against Foundation types which are almost always implicitly available so any file that was producing such output was successfully compiling.
A problem arises when the types that collide are _not_ within Foundation system framework but rather some custom frameworks.
This logic here updates to always qualify them if there are more than one found for a given type.

Always qualify ambiguous types

---

src/main/java/io/outfoxx/swiftpoet/CodeWriter.kt
src/main/java/io/outfoxx/swiftpoet/FileSpec.kt
src/test/java/io/outfoxx/swiftpoet/test/FileSpecTests.kt

If a type exists within a module that is being used by it and the same type exists in another module we do not properly disambiguate between them.
That is because we only keep track of `referenceTypeNames` that include a `moduleName`. This change collects the types used by the same module and properly disambiguates.

Correctly disambiguate conflicting type names between the module itself and external modules.

---

api/swiftpoet.api
src/main/java/io/outfoxx/swiftpoet/GenericQualifiedTypeName.kt
src/main/java/io/outfoxx/swiftpoet/GenericQualifier.kt
src/main/java/io/outfoxx/swiftpoet/TypeName.kt
src/test/java/io/outfoxx/swiftpoet/test/GenericQualifiedTypeNameTests.kt

Allows qualifying a `TypeName` with a generic qaulifier (`some` or `any`).
You qualify a type explicitly or using convenience on `TypeName`:
```swift
val myType = DeclaredTypeName.typeName(".MyType")
// Explicitly
GenericQualifiedTypeName.any(myType) // -> any MyType
// Convenience
myType.qualify(GenericQualifier.Any) // -> any MyType
```
Fixes #114

Support generic qualifiers for `TypeName`

---

.gitignore
src/main/java/io/outfoxx/swiftpoet/CodeWriter.kt
src/test/java/io/outfoxx/swiftpoet/test/FileSpecTests.kt

This treats `ExternalTypeSpec` and `TypeSpec` differently when resolving short names. Logically it makes sense because we basically assume that any nested `DeclaredTypeName` can be nested in a n `ExternalTypeSpec`, simply because there is no way to know what children it actually has.
A test was added for the case we found but, additionally, I added a test to ensure that nested naming for generated code (i.e. from `TypeSpec` other than `ExternalTypeSpec`) is handled the same way in extensions.

Fix shortening of nested names in generated hierarchies
